BEGIN TRANSACTION;
CREATE TABLE "Mana" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`long`	TEXT NOT NULL UNIQUE,
	`short`	TEXT NOT NULL UNIQUE
);
INSERT INTO `Mana` VALUES (1,'White','W');
INSERT INTO `Mana` VALUES (2,'Black','B');
INSERT INTO `Mana` VALUES (3,'Blue','U');
INSERT INTO `Mana` VALUES (4,'Red','R');
INSERT INTO `Mana` VALUES (5,'Green','G');
COMMIT;
